### ISSUE TITLE
Command Channel Filtering

### ISSUE THREAD

**Issue by emar10** [pg8wood/discord-voice-assistant-bot#1]
Many guilds would benefit from the ability to limit bot usage to a channel or a set of channels, allowing users to freely mute these channels and reduce notifications.

**Comment by HSocks1000** [comment]
A very simple solution is to mute our guild, Emar.

**Comment by pg8wood** [comment]
I think we'll keep a collection of allowed channels somewhere and check if the message is in an allowed channel. @emar10 I think having the bot mention the user in an allowed channel saying "plz post in here instead" will help guide the user toward the correct channel

**Comment by pg8wood** [comment]
The bot promised he'd stop spamming the other channels ❤️
